/**
 * @file main.c
 * @brief Minerva ATmega328P example — 4-class sensor classification
 *
 * Hardware: Arduino Uno (ATmega328P, 16 MHz)
 * Model: 16→32→16→4 MLP, Q8, encrypted with ChaCha20
 *
 * Pinout:
 *   A0–A3  : 4 analog sensor inputs (scaled to Q8)
 *   D2–D5  : 4 LED outputs (one per class)
 *   D13    : Error LED (blinks on security violation)
 *
 * The device key is stored in EEPROM page 0 (write-locked via fuse bits).
 * In production, use a hardware secure element or OTP fuse.
 *
 * Security behavior:
 *   MNV_ERR_TAMPER  → LED D13 blinks SOS, no inference
 *   MNV_ERR_GLITCH  → immediate WDT reset (via mnv_hal_fatal)
 *   MNV_ERR_INPUT   → discard sample, continue
 *   MNV_ERR_CONFIDENCE → output rejected, LED D13 single blink
 */

#include <avr/io.h>
#include <avr/pgmspace.h>
#include <avr/eeprom.h>
#include <util/delay.h>

/* Minerva: edit mnv_config.h for ATmega328P + MLP + Q8 first */
#include "minerva.h"
#include "weights.h"    /* generated by minerva_compile.py */
/* secrets.h defines MNV_DEVICE_KEY — never commit this file */
#include "secrets.h"

/* =========================================================================
 * HARDWARE ABSTRACTION
 * ========================================================================= */

#define LED_CLASS_0  PD2
#define LED_CLASS_1  PD3
#define LED_CLASS_2  PD4
#define LED_CLASS_3  PD5
#define LED_ERROR    PD13   /* PB5 on Uno */

static void hw_init(void)
{
    /* Output pins */
    DDRD |= (1<<LED_CLASS_0)|(1<<LED_CLASS_1)|(1<<LED_CLASS_2)|(1<<LED_CLASS_3);
    DDRB |= (1<<PB5);  /* D13 */

    /* ADC: AVcc reference, free-running disabled */
    ADMUX  = (1<<REFS0);                          /* AVcc reference */
    ADCSRA = (1<<ADEN)|(1<<ADPS2)|(1<<ADPS1);    /* Enable, prescaler 64 */
}

static uint16_t adc_read(uint8_t channel)
{
    ADMUX = (ADMUX & 0xF0) | (channel & 0x0F);
    ADCSRA |= (1<<ADSC);
    while (ADCSRA & (1<<ADSC));
    return ADC;
}

/* Scale 10-bit ADC [0,1023] to Q8 [-128,127] */
static int8_t adc_to_q8(uint16_t adc)
{
    return (int8_t)((int16_t)(adc >> 2) - 128);
}

static void led_set_class(uint8_t cls)
{
    uint8_t mask = (1<<LED_CLASS_0)|(1<<LED_CLASS_1)|(1<<LED_CLASS_2)|(1<<LED_CLASS_3);
    PORTD = (PORTD & ~mask) | (1 << (LED_CLASS_0 + cls));
}

static void led_error_blink(uint8_t n)
{
    for (uint8_t i = 0; i < n; i++) {
        PORTB |=  (1<<PB5);
        _delay_ms(200);
        PORTB &= ~(1<<PB5);
        _delay_ms(200);
    }
}

/* =========================================================================
 * MAIN
 * ========================================================================= */

/* Static context — zero-initialized by linker (BSS) */
static mnv_ctx_t minerva_ctx;

int main(void)
{
    hw_init();

    /* Startup blink — 3 flashes indicate Minerva initializing */
    led_error_blink(3);

    /* Initialize Minerva — this runs the BLAKE2s integrity check */
    mnv_status_t status = mnv_init(&minerva_ctx, &mnv_model);
    if (status != MNV_OK) {
        /* Integrity check failed at boot — blink SOS indefinitely */
        while (1) {
            led_error_blink(3); _delay_ms(200);
            led_error_blink(3); _delay_ms(200);
            led_error_blink(3); _delay_ms(600);
        }
    }

    /* Ready — two slow blinks */
    led_error_blink(2);

    /* Main inference loop */
    while (1) {
        /* Read 4 sensors → Q8 input vector */
        int8_t input[MNV_INPUT_SIZE];
        input[0]  = adc_to_q8(adc_read(0));
        input[1]  = adc_to_q8(adc_read(1));
        input[2]  = adc_to_q8(adc_read(2));
        input[3]  = adc_to_q8(adc_read(3));
        /* Remaining inputs set to zero (unused in this example) */
        for (uint8_t i = 4; i < MNV_INPUT_SIZE; i++) input[i] = 0;

        /* Run inference */
        int8_t output[MNV_OUTPUT_SIZE];
        status = mnv_run_with_model(&minerva_ctx, &mnv_model,
                                    (const mnv_act_t *)input,
                                    (mnv_act_t *)output);

        switch (status) {
            case MNV_OK: {
                /* Find predicted class (argmax) */
                uint8_t cls = mnv_ct_argmax((const mnv_act_t *)output, MNV_OUTPUT_SIZE);
                led_set_class(cls);
                break;
            }
            case MNV_ERR_TAMPER:
            case MNV_ERR_GLITCH:
                /* Fatal — WDT resets device (configured in mnv_hal_avr.c) */
                while (1) led_error_blink(1);
                break;
            case MNV_ERR_CONFIDENCE:
                /* Low confidence — extinguish class LEDs, single error blink */
                PORTD &= ~((1<<LED_CLASS_0)|(1<<LED_CLASS_1)|(1<<LED_CLASS_2)|(1<<LED_CLASS_3));
                led_error_blink(1);
                break;
            default:
                led_error_blink(2);
                break;
        }

        _delay_ms(50);  /* ~20 Hz inference rate */
    }
}
